definitions: {}
info:
  description: powered by Flasgger
  termsOfService: /tos
  title: A swagger API
  version: 0.0.1
paths:
  /contacts:
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            name:
              type: string
            phone:
              type: string
          required:
          - name
          - phone
          type: object
      responses:
        '201':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0441\u043E\u0437\
            \u0434\u0430\u043D"
          schema:
            properties:
              id:
                type: integer
              name:
                type: string
              phone:
                type: string
            type: object
      tags:
      - Contacts
  /contacts/{contact_id}:
    delete:
      parameters:
      - description: "\u0418\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\
          \u0442\u043E\u0440 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        in: path
        name: contact_id
        required: true
        type: integer
      responses:
        '200':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0443\u0434\u0430\
            \u043B\u0451\u043D"
        '404':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
      tags:
      - Contacts
    get:
      description: "\u041E\u0441\u043D\u043E\u0432\u043D\u043E\u0439 GET-\u0437\u0430\
        \u043F\u0440\u043E\u0441 \u0434\u043B\u044F \u0447\u0442\u0435\u043D\u0438\
        \u044F \u0434\u0430\u043D\u043D\u044B\u0445 \u0442\u0435\u043B\u0435\u0444\
        \u043E\u043D\u043D\u043E\u0439 \u043A\u043D\u0438\u0433\u0438. \u0418\u0441\
        \u043F\u043E\u043B\u044C\u0437\u0443\u0435\u0442\u0441\u044F \u0432\u043D\u0435\
        \u0448\u043D\u0438\u043C\u0438 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\
        \u0442\u0435\u043B\u044F\u043C\u0438 \u0434\u043B\u044F \u043F\u043E\u043B\
        \u0443\u0447\u0435\u043D\u0438\u044F \u0438\u043D\u0444\u043E\u0440\u043C\u0430\
        \u0446\u0438\u0438 \u043E \u043A\u043E\u043D\u043A\u0440\u0435\u0442\u043D\
        \u043E\u043C \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0435 \u043F\u043E\
        \ \u0435\u0433\u043E \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\
        \u0430\u0442\u043E\u0440\u0443."
      parameters:
      - description: "\u0423\u043D\u0438\u043A\u0430\u043B\u044C\u043D\u044B\u0439\
          \ \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\
          \u0440 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        example: 1
        in: path
        name: contact_id
        required: true
        type: integer
      responses:
        '200':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0430\u0439\
            \u0434\u0435\u043D"
          schema:
            properties:
              id:
                example: 1
                type: integer
              name:
                example: "\u0418\u0432\u0430\u043D \u0418\u0432\u0430\u043D\u043E\u0432"
                type: string
              phone:
                example: '+79990001122'
                type: string
            type: object
        '404':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0441 \u0442\u0430\
            \u043A\u0438\u043C \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\
            \u0430\u0442\u043E\u0440\u043E\u043C \u043D\u0435 \u043D\u0430\u0439\u0434\
            \u0435\u043D"
          schema:
            properties:
              error:
                example: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435\
                  \ \u043D\u0430\u0439\u0434\u0435\u043D"
                type: string
            type: object
      tags:
      - Contacts
swagger: '2.0'
